### ISSUE TITLE
geb.image doesn't work (or I'm doing something wrong)

### ISSUE THREAD

**Issue by lukaszcz** [anoma/geb#47]
I have a file `my.lisp`:
```lisp
(defpackage #:my
  (:shadowing-import-from :geb.lambda.spec #:func #:pair)
  (:shadowing-import-from :geb.spec #:case)
  (:use #:common-lisp #:geb.lambda.spec #:geb))

(in-package :my)

(defparameter *entry*
  (typed unit so1))
```
I run:
```
geb.image -i my.lisp -e "my::*entry*" -l
```
I get:
```
debugger invoked on a SB-KERNEL:CASE-FAILURE @52D72F01 in thread
#<THREAD "main thread" RUNNING {1001A50003}>:
  (->1 s-1) fell through ETYPECASE expression.
  Wanted one of (SIMPLE-STRING STRING SB-FORMAT::FMT-CONTROL).
```
I was unable to come up with an input for `geb.image` which wouldn't cause some kind of error.

**Comment by mariari** [comment]
The latest commit fixes the issue, overlooked a minor part of the integration code in a rush to get out the binary my bad.


```lisp
taichi@Gensokyo:~/Documents/Work/Repo/geb/build git:main:*? % cat foo.lisp                                     
(defpackage #:foo
  (:shadowing-import-from :geb.lambda.spec #:func #:pair)
  (:shadowing-import-from :geb.spec #:case)
  (:use #:common-lisp #:geb.lambda.spec #:geb))

(in-package :foo)

(defparameter *entry*
  (typed unit so1))

taichi@Gensokyo:~/Documents/Work/Repo/geb/build git:main:*? % ./geb.image -i "foo.lisp" -e "foo::*entry*" -l
(->1 s-1)%                                                                                                         
taichi@Gensokyo:~/Documents/Work/Repo/geb/build git:main:*? % ./geb.image -i "foo.lisp" -e "foo::*entry*" -l -v
def *entry* x = {
  0
};%                                                                                                                
```

is an example usage if you passed `-v` you would get out vampir

**Comment by lukaszcz** [comment]
Now I have:
```lisp
(defparameter *entry*
  (typed (app (coprod so1 so1) (coprod so1 so1) (lamb (coprod so1 so1) (coprod so1 so1) (index 0)) (left unit)) (coprod so1 so1)))
```
And I get:
```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1001A30003}>:
  Types should match for application: (+ s-1 s-1) (+ s-1 s-1)
```
Did I misunderstand the meaning of `dom` and `cod` in the `app` constructor in `lambda.lisp`?

**Comment by rokopt** [comment]
> Now I have:
> 
> ```lisp
> (defparameter *entry*
>   (typed (app (coprod so1 so1) (coprod so1 so1) (lamb (coprod so1 so1) (coprod so1 so1) (index 0)) (left unit)) (coprod so1 so1)))
> ```
> 
> And I get:
> 
> ```
> debugger invoked on a SIMPLE-ERROR in thread
> #<THREAD "main thread" RUNNING {1001A30003}>:
>   Types should match for application: (+ s-1 s-1) (+ s-1 s-1)
> ```
> 
> Did I misunderstand the meaning of `dom` and `cod` in the `app` constructor in `lambda.lisp`?

I'll take a look at this.

**Comment by mariari** [comment]
> 

Looked at it, the problem was that we were using too strict of equality, thanks for submitting a bug report, here is a graph of your computation we will submit the patch soon. Thanks

https://pomf2.lain.la/f/ioly9p0m.png

**Comment by rokopt** [comment]
> Now I have:
> 
> ```lisp
> (defparameter *entry*
>   (typed (app (coprod so1 so1) (coprod so1 so1) (lamb (coprod so1 so1) (coprod so1 so1) (index 0)) (left unit)) (coprod so1 so1)))
> ```
> 
> And I get:
> 
> ```
> debugger invoked on a SIMPLE-ERROR in thread
> #<THREAD "main thread" RUNNING {1001A30003}>:
>   Types should match for application: (+ s-1 s-1) (+ s-1 s-1)
> ```
> 
> Did I misunderstand the meaning of `dom` and `cod` in the `app` constructor in `lambda.lisp`?

Does https://github.com/anoma/geb/pull/48 fix it?

**Comment by lukaszcz** [comment]
> 

No I get the error:
```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1001A28003}>:
  mod logic not in yet

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

((:METHOD GEB.POLY.TRANS:TO-VAMPIR (GEB.POLY.SPEC:IF-LT T)) #<unused argument> #<unused argument>) [fast-method]
   source: (ERROR "mod logic not in yet")
```

**Comment by lukaszcz** [comment]
Also for `case-on`:
```
(defparameter *entry*
  (typed (case-on so1 so1 (coprod so1 so1) (left unit) (lamb so1 (coprod so1 so1) (right unit)) (lamb so1 (coprod so1 so1) (left unit))) (coprod so1 so1)))
```
I get this error:
```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1001A28003}>:
  object (∘ (∘ (∘ (->right s-1 s-1) (->1 (× s-1 s-1 s-1)))
               ((<-right (× s-1 s-1) s-1) (<-left (× s-1 s-1) s-1)))
            (s-1
             (->1 (× s-1
                     s-1)))) need to be of a product type, however it is of s-1

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

((:METHOD GEB.MAIN:CURRY (GEB.SPEC:<SUBSTMORPH>)) (∘ (∘ (∘ (->right #1=s-1 #1#) (->1 (× #1# #1# #1#))) ((<-right #2=(× #1# #1#) #1#) (<-left #2# #1#))) (#1# (->1 #2#)))) [fast-method]
   source: (ERROR "object ~A need to be of a product type, however it is of ~A"
                  F (DOM F))
```

**Comment by mariari** [comment]
> > 
> 
> No I get the error:
> 
> ```
> debugger invoked on a SIMPLE-ERROR in thread
> #<THREAD "main thread" RUNNING {1001A28003}>:
>   mod logic not in yet
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [ABORT] Exit from the current thread.
> 
> ((:METHOD GEB.POLY.TRANS:TO-VAMPIR (GEB.POLY.SPEC:IF-LT T)) #<unused argument> #<unused argument>) [fast-method]
>    source: (ERROR "mod logic not in yet")
> ```

```lisp
(ERROR "mod logic not in yet")
```
Mod logic is not in for vampir yet, so it's failing there, works if you don't pass in `-v` since it doesn't go that far down

**Comment by lukaszcz** [comment]
> > > 
> > 
> > 
> > No I get the error:
> > ```
> > debugger invoked on a SIMPLE-ERROR in thread
> > #<THREAD "main thread" RUNNING {1001A28003}>:
> >   mod logic not in yet
> > 
> > Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> > 
> > restarts (invokable by number or by possibly-abbreviated name):
> >   0: [ABORT] Exit from the current thread.
> > 
> > ((:METHOD GEB.POLY.TRANS:TO-VAMPIR (GEB.POLY.SPEC:IF-LT T)) #<unused argument> #<unused argument>) [fast-method]
> >    source: (ERROR "mod logic not in yet")
> > ```
> 
> ```lisp
> (ERROR "mod logic not in yet")
> ```
> 
> Mod logic is not in for vampir yet, so it's failing there, works if you don't pass in `-v` since it doesn't go that far down

Yes, it seems to work without the `-v`

**Comment by mariari** [comment]
> > > > 
> > > 
> > > 
> > > No I get the error:
> > > ```
> > > debugger invoked on a SIMPLE-ERROR in thread
> > > #<THREAD "main thread" RUNNING {1001A28003}>:
> > >   mod logic not in yet
> > > 
> > > Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> > > 
> > > restarts (invokable by number or by possibly-abbreviated name):
> > >   0: [ABORT] Exit from the current thread.
> > > 
> > > ((:METHOD GEB.POLY.TRANS:TO-VAMPIR (GEB.POLY.SPEC:IF-LT T)) #<unused argument> #<unused argument>) [fast-method]
> > >    source: (ERROR "mod logic not in yet")
> > > ```
> > 
> > 
> > ```lisp
> > (ERROR "mod logic not in yet")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Mod logic is not in for vampir yet, so it's failing there, works if you don't pass in `-v` since it doesn't go that far down
> 
> Yes, it seems to work without the `-v`

the visual [I posted earlier](https://pomf2.lain.la/f/ioly9p0m.png) was from this output, I can make it a feature of the binary if you want, since it's a simple call

**Comment by rokopt** [comment]
> > 
> 
> Now I get the error:
> 
> ```
> debugger invoked on a SIMPLE-ERROR in thread
> #<THREAD "main thread" RUNNING {1001A28003}>:
>   mod logic not in yet
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [ABORT] Exit from the current thread.
> 
> ((:METHOD GEB.POLY.TRANS:TO-VAMPIR (GEB.POLY.SPEC:IF-LT T)) #<unused argument> #<unused argument>) [fast-method]
>    source: (ERROR "mod logic not in yet")
> ```

See #57 for updates on our getting this implemented.

**Comment by rokopt** [comment]
> Also for `case-on`:
> 
> ```
> (defparameter *entry*
>   (typed (case-on so1 so1 (coprod so1 so1) (left unit) (lamb so1 (coprod so1 so1) (right unit)) (lamb so1 (coprod so1 so1) (left unit))) (coprod so1 so1)))
> ```
> 
> I get this error:
> 
> ```
> debugger invoked on a SIMPLE-ERROR in thread
> #<THREAD "main thread" RUNNING {1001A28003}>:
>   object (∘ (∘ (∘ (->right s-1 s-1) (->1 (× s-1 s-1 s-1)))
>                ((<-right (× s-1 s-1) s-1) (<-left (× s-1 s-1) s-1)))
>             (s-1
>              (->1 (× s-1
>                      s-1)))) need to be of a product type, however it is of s-1
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [ABORT] Exit from the current thread.
> 
> ((:METHOD GEB.MAIN:CURRY (GEB.SPEC:<SUBSTMORPH>)) (∘ (∘ (∘ (->right #1=s-1 #1#) (->1 (× #1# #1# #1#))) ((<-right #2=(× #1# #1#) #1#) (<-left #2# #1#))) (#1# (->1 #2#)))) [fast-method]
>    source: (ERROR "object ~A need to be of a product type, however it is of ~A"
>                   F (DOM F))
> ```

I'll investigate this.  I've filed #58 to track it.

**Comment by rokopt** [comment]
I believe that all of the problems described in this issue (which have had sub-issues filed to track them independently) have now been addressed, so I'm going to close this one.  Please file new issues for any further problems.  Thanks!
