### ISSUE TITLE
Missing type/object for left and right morphisms

### ISSUE THREAD

**Issue by jonaprieto** [anoma/geb#53]
Please consider adding the Object information missing from the left and right morphisms.
Say `left a` is of object `coprod A B`, I expect to write in the future `left a B`, as the object for `a` can be inferred. We plan to use this info to have a simple type-checking/inference algorithm for the Geb backend of Juvix.

**Comment by lukaszcz** [comment]
It's about your `stlc` datastructure (https://github.com/anoma/geb/blob/main/src/specs/lambda.lisp). If you don't have the type info about missing option in left/right coproduct injection, then not every term has a unique type. That's also the case when you don't have the result type specified in the `absurd` constructor (which you don't), so also consider adding that one.

**Comment by rokopt** [comment]
Agreed, we'll add these.

**Comment by rokopt** [comment]
#70 includes code to address this (including for `absurd` as well as `left` and `right`).

**Comment by rokopt** [comment]
Done in #81 .
