### ISSUE TITLE
Test failure in `WEAK-POINTERS-WORK`

### ISSUE THREAD

**Issue by rokopt** [anoma/geb#73]
When I run `(asdf:test-system :geb)` from the `sbcl` command line, I get one failure:

```
;; Failures:
   1/   6 tests failed in GEB-TEST::GEB-TEST-SUITE
   1/   2 tests failed in GEB-TEST::GEB-META
   1/   1 tests failed in GEB-TEST::WEAK-POINTERS-WORK
The test form   count
evaluated to    0
when            1
was expected to be equal under =.
```

**Comment by mariari** [comment]
What version of SBCL are you running?

I noticed it on the CI too (sadly I don't throw when an error occurs, so it turns out the CI doesn't catch failures in the tests...)

**Comment by rokopt** [comment]
> What version of SBCL are you running?
> 
> I noticed it on the CI too (sadly I don't throw when an error occurs, so it turns out the CI doesn't catch failures in the tests...)

```
❯ sbcl --version
SBCL 2.1.11.debian
```

**Comment by mariari** [comment]
I get a similar result with `sbcl 2.2.6`. Seems SBCL imrpoved it's GC to actually collect newly defined references
