### ISSUE TITLE
Geb input format changed

### ISSUE THREAD

**Issue by lukaszcz** [anoma/geb#95]
The latest version (on main) doesn't parse the files we generate anymore. It complains:
```
  no symbol named "FUNC" in "GEB.LAMBDA.SPEC"
```

The input format should be specified somewhere, and the specification updated with changes.

**Comment by agureev** [comment]
We have documentation covering almost all of the interface.

https://anoma.github.io/geb/#toc-10-3-transition-functions

covers how `compile-checked-term` now works and 

https://anoma.github.io/geb/#toc-10-1-lambda-specification

covers all of the constructors. In particular the `func` issue has to do with the `app` constructor.

**Comment by lukaszcz** [comment]
Okay, thanks!

**Comment by rokopt** [comment]
Please let us know if working off this documentation allows you to update to the new format, and once it does, we'll close it (or feel free to close it yourself).
